### ISSUE TITLE
`call` instructions get reported as an undefined label

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#10]
Visual Studio 2015 Update 2
AsmDude version 1.5.0.1

Here's a small asm file:

    segment_name SEGMENT USE64
        call proc_name
        hlt
    
    proc_name PROC
        xor rax, rax
        ret
    proc_name ENDP
    segment_name ENDS

Open this file in Visual Studio and AsmDude will report `call proc_name` as having an "Undefined Label".

**Comment by HJLebbink** [comment]
Thanks for reporting, 

The Masm procedure block identifier is not added to the label graph. I'll fix that in the next few days.

**Comment by HJLebbink** [comment]
Version 1.5.0.2 supports the Masm procedure block properly
