### ISSUE TITLE
Cannot resolve ksamd64.inc

### ISSUE THREAD

**Issue by NN---** [HJLebbink/asm-dude#103]
ksamd64.inc is defined in Windows SDK, but AsmDude cannot find it.

Sample with `include ksamd64.inc`
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/floating-point-support-for-64-bit-drivers

**Comment by HJLebbink** [comment]
The include directive is _relative_. When you write `include ksamd64.inc` in file X, it means AmsDude expects to find the file ksamd64.inc in the same directory in which X resides.
