### ISSUE TITLE
Feature Request: Option to disable code folding for large files.

### ISSUE THREAD

**Issue by AHUMANTHATISHUMAN** [HJLebbink/asm-dude#105]
Currently, the performance of code folding on large files, such as the assembler output, is terrible. For example, a 1.25mb assembly file generated by the compiler caused Visual Studio to hand for over 120 seconds. Disabling code folding requires a VS restart.

Could you add an option to add a file size limit for code folding, add a time limit, or both?

**Comment by HJLebbink** [comment]
I'll look into it. I thought I added a mechanism that when folding took longer than several seconds, folding is disabled. I'll add a file size limit for code folding.

**Comment by AHUMANTHATISHUMAN** [comment]
It just says that code folding performance is horrible and suggests disabling it, which requires a VS restart.

**Comment by HJLebbink** [comment]
Version 1.9.6.14 has configurable MaxLines (default 50000). I hope this solves your issues. Let me know if it does not.
