### ISSUE TITLE
file content check / large file handling

### ISSUE THREAD

**Issue by Trass3r** [HJLebbink/asm-dude#106]
LLVM uses huge generated .inc files (80000 lines) containing C++ code. AsmDude tries to handle them as assembly code and VS freezes completely, 2 cores busy. Disabled AsmDude to confirm it fixes the problem.

I guess there should be some kind of sanity check if it's actually assembly code and/or some mechanism to handle large files in a better way.

**Comment by HJLebbink** [comment]
Yes, a sanity check for code content makes sense, and if no assembly is found than ignore the file. Sadly, since the file extension (.inc) is associated with assembly, no c++ highlighting etc will occur. Will look at it shorthly.

**Comment by Trass3r** [comment]
Well there's also Options->Text Editor->File Extension. I haven't tested yet how this interacts with your extension.

**Comment by Trass3r** [comment]
Btw large file handling could also be better for asm:

```
WARNING: SLOW: took LabelGraph 4.052 seconds to finish
WARNING: Performance of LabelGraph is horrible: disabling label analysis for tmp.asm.
WARNING: Performance of LabelGraph is horrible: disabling label analysis for tmp.asm.
WARNING: could not highlight string ""))"; e=parsing ""))" - Too many )'s.
WARNING: SLOW: took HighlightWordTagger 0.750 seconds to finish
WARNING: SLOW: took HighlightWordTagger 9.933 seconds to finish
WARNING: SLOW: took CodeFoldingTagger 228.646 seconds to finish
WARNING: Performance of CodeFoldingTagger is horrible: disabling folding for .
WARNING: Performance of CodeFoldingTagger is horrible: disabling folding for .
```

**Comment by HJLebbink** [comment]
Added configurable MaxLines to handle very large files. I hope this solves your issues, if it does not, do let me know.
