### ISSUE TITLE
Keywords inside of strings are not ignored

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#11]
Example file:

    segment_name SEGMENT USE64
        db "This string contains the word jmp inside of it",0
    segment_name ENDS

Having syntax coloring inside of these strings is not a huge problem.  The bigger issue is that the word "inside" shows up in Visual Studio's error list as "Undefined Label"

**Comment by HJLebbink** [comment]
Nice one, didn't think about that,

The next release (after 1.5.0.2) will have this fixed.
