### ISSUE TITLE
horrible slow

### ISSUE THREAD

**Issue by Nic4712** [HJLebbink/asm-dude#114]
Welcome to
 _____             ____        _     
|  _  |___ _____  |    \ _ _ _| |___ 
|     |_ -|     | |  |  | | | . | -_|
|__|__|___|_|_|_| |____/|___|___|___|
INFO: Loaded AsmDude version 1.9.6.14 (29.09.2019 20:26:34)
INFO: Open source assembly extension. Making programming in assembler almost bearable.
INFO: More info at https://github.com/HJLebbink/asm-dude 
----------------------------------
WARNING: SLOW: took LabelGraph 50,959 seconds to finish
WARNING: Performance of LabelGraph is horrible: disabling label analysis for E:\ASM\.....asm.
WARNING: Performance of LabelGraph is horrible: disabling label analysis for E:\ASM\.....asm.
WARNING: SLOW: took CodeFoldingTagger 97,813 seconds to finish
ERROR: AsmDudeToolsStatic:GetFilename; could not get filename within timeout 200 ms
WARNING: Performance of CodeFoldingTagger is horrible: disabling folding for .
WARNING: Performance of CodeFoldingTagger is horrible: disabling folding for .
WARNING: SLOW: took HighlightWordTagger 3,838 seconds to finish
WARNING: SLOW: took HighlightWordTagger 3,589 seconds to finish
WARNING: SLOW: took HighlightWordTagger 3,831 seconds to finish

**Comment by minefedt** [comment]
Lol

**Comment by sherrifmarty** [comment]
Hi, I sometimes get this email and o don't know how to unsubscribe since i
don't know my GitHub login info. Could you unsubscribe me?

Greetings Marten

Op za 10 okt. 2020 18:48 schreef Nic4712 <notifications@github.com>:

**Comment by joshato** [comment]
Remove me to. I NEVER signed up for this shit in the first, haven't used
github in years.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Nic4712** [comment]
Hello!
this program is quite good in itself, but maybe because of the PDF parser for a simple ASM file and VS2019 it is simply not optimal.
The only question was whether the author is informed about this shortcoming and whether he is working on it or, since he knows his program, can make a suggestion as to where to start in order to make faster progress.
Nic

**Comment by joshato** [comment]
UNSUBSCRIBE

**Comment by HJLebbink** [comment]
@Nic4712 The different taggers (HighlightWordTagger, CodeFoldingTagger, etc) in AsmDude are written on the VS api for tagging words. These tagging methods do not scale nicely with large files of say 10'000 lines. If AsmDude encounters a very slow operation, it disables that feature for that specific file only. 

However, if you encounter a reasonable sized file and yet these taggers (or AsmDude) is very slow, do let me know. I can give a look.

**Comment by Nic4712** [comment]
@HJLebbink 
it`s an old 8086 asm with over 25 000 lines
and some more when debugging
then VS stops.
If windows.inc is added, then only Str-Alt-Del helps.
On the other hand, it was only about working with the colored background.
nic

**Comment by HJLebbink** [comment]
You can disable code folding and disable label analysis. Could you post the .asm file than I can also give it a look.

**Comment by joshato** [comment]
REMOVE ME FROM THIS FUCKING LIST. I DON'T HAVE ACCESS TO THE ACCOUNT.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by chadclancy** [comment]
Why am I receiving email notifications from this thread. I am not subscribed to this thread. I've never looked at this project before. WTF

**Comment by joshato** [comment]
UNSUBSCRIBE ME. I WILL CONTINUE TO REPLY ALL TO THESE EMAILS UNTIL YOU DO.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by novagamerhd** [comment]
If I continue to get these emails, I swear to fucking god.
