### ISSUE TITLE
change highlighting in visual studio 2019

### ISSUE THREAD

**Issue by HoomanT** [HJLebbink/asm-dude#117]
I found the configuration file And the contents are like this:
```
<register name='RAX' bits='64' arch='X64'>
	<description>64-bit GPR (Accumulator)</description>
</register>
```
My question is how can I change the highlighting & coloring of them? what attribute should I add or change 
to these xml tags to control the color?

**Comment by HJLebbink** [comment]
@HoomanT In Visual Studio, go to Tools/Options/AsmDude/Syntax Highlighting. The config file you dug up is for descriptions.
