### ISSUE TITLE
Highlight issue in dark mode

### ISSUE THREAD

**Issue by iawindowss** [HJLebbink/asm-dude#118]
I don't know if I am just being stupid but 
![strange](https://user-images.githubusercontent.com/65748956/101840751-b1995c00-3b12-11eb-8746-56a273fd1c85.PNG)
It works completely fine in any other color theme like blue or light. Dark just does that.

**Comment by HJLebbink** [comment]
I never used Dark theme, I guess that since I'm the last one using light theme, I should give it a try... 

Is your issue solved?

**Comment by rilwing** [comment]
Hi.
In 2023 this issue still here.

**Comment by rilwing** [comment]
Tools -> Import and Export Settings -> Reset all settings
It fixed this problem for me

**Comment by HJLebbink** [comment]
Yes, AsmDude2 will reuse any settings that could still be present from (another VS installation 2019, with) AsmDude. I hope this will not bite those who have both VS2022 and VS2019 installed, and need to have different settings for both installs...
