### ISSUE TITLE
The dollar sign is considered an undefined label

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#12]
It's common for us to write "breakpoints" in using jump instructions to $.  Example file:

    segment_name SEGMENT USE64
        jmp $
    segment_name ENDS

This shows up in the error list as an undefined label.

**Comment by HJLebbink** [comment]
Thanx for mentioning. The $ character is ignored when it is encountered on a label definition position.

The next release (after 1.5.0.2) will have this fixed.
