### ISSUE TITLE
VS 2019 - Could not resolve Include Bug

### ISSUE THREAD

**Issue by ethanr0x** [HJLebbink/asm-dude#120]
New to assembly, so be nice :)

Added an *.inc file in the same folder as .asm file.
MASM include path is empty.
![image](https://user-images.githubusercontent.com/6856739/106539785-4747db00-6507-11eb-9052-b74f2bdc9c64.png)

It successfully finds the procedure, but for the INCLUDE - "Could not resolve include".
EDIT:
If all of the rest of "dependencies" for the *.inc file are in place **in the same folder as .asm** - no underlines. If it is written in relative path mod "../.." with all of its dependencies there - it will have underlines, but not the procedure. 

EDIT2:
Turns out I messed up the relative path syntax, I guess.
If one makes a directory AsmDudeInc next to the source files and writes:

`INCLUDE AsmDudeInc/Irvine32.inc `

everything works beautifully. As long as the include paths from the project configuration cannot be scanned by AsmDude, this seems like the cleanest solution atm.

**Comment by zeronohacker** [comment]
I have the same problem.

**Comment by ickoxii** [comment]
I have the same problem too, I can only run my code if I disable asmdude, which itself isn't the most straightforward thing to do

**Comment by ethanr0x** [comment]
This is not issue with AsmDude. The "bug" I experienced was due to the fact that Irvine32.inc has two other includes in it which weren't in the directory with the asm files. See second EDIT for solution to the issue

**Comment by HJLebbink** [comment]
@ethanr0x Thanx for reporting back and resolving the issue. I'm quite bussy at the moment address these issues.

**Comment by ethanr0x** [comment]
> 
> 
> @ethanr0x Thanx for reporting back and resolving the issue. I'm quite busy at the moment address these issues.

np. there is still some issue with underlines even with the proposed solution. Seems very tricky though, cannot really reproduce. One case is if I have an empty line after include, it works - if there is no new line, there are underlines. I might make a new issue with a more detailed report and workarounds in the future.

At the time, it doesn't cause all that much inconvenience.
