### ISSUE TITLE
VS2022 - No Screen effect at all

### ISSUE THREAD

**Issue by DBenS** [HJLebbink/asm-dude#138]
Hi,

I installed the preview VS2022 version, and everything seemed to be 100% (properties page on TOOLS - OPTIONS- ASMDUDE and TOOLS FONTS), but I can't see any color (they're all ON now) and intellicode.

I started my code through a C++ Empty project. 

I appreciate any help on this.

**Comment by Jollydonkey** [comment]
It can only be applied on VS 2013 2015 and 2019.

**Comment by HJLebbink** [comment]
for VS2022 support, see https://github.com/SnellerInc/asm-dude/discussions/1
