### ISSUE TITLE
Workaround for labels defined in other files?

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#15]
I have a hunch this will be difficult to get working properly, but let's say you have these files:

### a.asm

    include "a.inc"
    segment_name SEGMENT USE64
        jmp mylabel
    segment_name ENDS

### a.inc

    inc_segment_name SEGMENT USE64
        mylabel:
        hlt
    inc_segment_name ENDS

"mylabel" is considered an undefined label, even though it will be defined once "a.inc" is included into the file.

We use this a lot and it results in AsmDude writing many "Undefined Label" warnings in Visual Studio's Error List.

Any ideas?

**Comment by HJLebbink** [comment]
I'll give it a try, shouldn't be too difficult. Give me a few days to test it.

**Comment by Tinister** [comment]
Thanks.

Do you think it can support the inverse?  (jmp in "a.inc", label definition in "a.asm")  My gut feeling is that would be even harder.

**Comment by HJLebbink** [comment]
Includes can be read as "get me the content of that file and assume this content is here". I'm more worried about resolving network drives, relative paths, and other funky ways the include mechanism can have been misused.

**Comment by sajadbanooie** [comment]
externed labels should be considered too.
`extern _printf
.
.
.
call _printf`

**Comment by HJLebbink** [comment]
I've added support for (Masm) includes, the Nasm alternatives will be added in the full release. If you find issues, please report those. Regards.

[Version 1.5.1.0](https://github.com/HJLebbink/asm-dude/releases/tag/1.5.1.0)

**Comment by HJLebbink** [comment]
Found a silly bug in 1.5.1.0. Please use [Version 1.5.1.1](https://github.com/HJLebbink/asm-dude/releases/tag/1.5.1.1)
