### ISSUE TITLE
[machine translation]Incomplete highlighting of the latest version of the code

### ISSUE THREAD

**Issue by good768** [HJLebbink/asm-dude#152]
Thank you to the developer for creating this extension :)
The code highlighting is complete in the first version you released
![屏幕截图 2023-10-07 211844](https://github.com/HJLebbink/asm-dude/assets/64065417/aca0fe08-60c1-4215-8e98-5c5a886ce145)
![屏幕截图 2023-10-07 212009](https://github.com/HJLebbink/asm-dude/assets/64065417/a71eb3f2-c2ca-48ea-adc3-a1dd5e8c05f9)
But in the latest version, it will become as shown in the following picture
![屏幕截图 2023-10-07 212755](https://github.com/HJLebbink/asm-dude/assets/64065417/53945865-a5b8-4f28-8a9b-8584f33b2501)
And there will also be this pop-up window
![屏幕截图 2023-10-07 212900](https://github.com/HJLebbink/asm-dude/assets/64065417/2974b1c1-f6ec-48ee-9feb-f2cfa0a651d9)
Sorry, my English is very plastic and I am a beginner :.(

**Comment by HJLebbink** [comment]
The Language server protocol run in a different process (and has a window that you posted above), that window hides itself directly after the process is created, but when it observes an error, it show itself again. Given that you could make a screenshot of it, I assume the error message is somewhere at the bottom of this screen. The warnings you see in the screenshot are not important, I just didn't have time to look at them. Could you give me a screenshot of the message that starts with ERROR?

**Comment by good768** [comment]
info: AsmDude2LS.Worker[0]
      Worker created at: 10/11/2023 21:02:47 +08:00
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: c:\users\29269\appdata\local\microsoft\visualstudio\17.0_d5512606\extensions\tl15c0ek.fpz\Server
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CLAC; doc =Clear the AC flag in the EFLAGS register.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CLWB; doc =Writes back modified cache line containing m8, and may retain the line in cache hierarchy in non-modified state.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG; doc =Compare AL with r/m8. If equal, ZF is set and r8 is loaded into r/m8. Else, clear ZF and load r/m8 into AL.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG; doc =Compare AL with r/m8. If equal, ZF is set and r8 is loaded into r/m8. Else, clear ZF and load r/m8 into AL.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG; doc =Compare AX with r/m16. If equal, ZF is set and r16 is loaded into r/m16. Else, clear ZF and load r/m16 into AX.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG; doc =Compare EAX with r/m32. If equal, ZF is set and r32 is loaded into r/m32. Else, clear ZF and load r/m32 into EAX.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG; doc =Compare RAX with r/m64. If equal, ZF is set and r64 is loaded into r/m64. Else, clear ZF and load r/m64 into RAX.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG8B; doc =Compare EDX:EAX with m64. If equal, set ZF and load ECX:EBX into m64. Else, clear ZF and load m64 into EDX:EAX.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CMPXCHG16B; doc =Compare RDX:RAX with m128. If equal, set ZF and load RCX:RBX into m128. Else, clear ZF and load m128 into RDX:RAX.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m8.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m8.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m16.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m32.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m8.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CRC32; doc =Accumulate CRC32 on r/m64.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTPD2PI; doc =Convert two packed DP FP values from xmm/m128 to two packed signed doubleword integers in mm.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTPI2PD; doc =Convert two packed signed doubleword integers from mm/mem64 to two packed DP FP values in xmm.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTPI2PS; doc =Convert two signed doubleword integers from mm/m64 to two SP FP values in xmm.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTPS2PI; doc =Convert two packed SP FP values from xmm/m64 to two packed signed doubleword integers in mm.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTTPD2PI; doc =Convert two packer DP FP values from xmm/m128 to two packed signed doubleword integers in mm using truncation.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=CVTTPS2PI; doc =Convert two SP FP values from xmm/m64 to two signed doubleword signed integers in mm using truncation.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=EDECVIRTCHILD; doc =This leaf function decrements the SECS VIRTCHILDCNT field.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=EINCVIRTCHILD; doc =This leaf function increments the SECS VIRTCHILDCNT field.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ELDBC; doc =This leaf function behaves lie ELDB but with improved conflict handling for oversubscription.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ELDBC; doc =This leaf function behaves like ELDU but with improved conflict handling for oversubscription.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ENCLS; doc =This instruction is used to execute privileged Intel SGX leaf functions that are used for managing and debugging the enclaves.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ENCLU; doc =This instruction is used to execute non-privileged Intel SGX leaf functions.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ENCLV; doc =This instruction is used to execute privileged SGX leaf functions that are reserved for VMM use. They are used for managing the enclaves.
AsmSignatureTools:parseOperandTypeEnum: unknown content 64
AsmSignatureTools:parseOperandTypeEnum: unknown content 64
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ERDINFO; doc =This leaf function returns type and status information about an EPC page.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ESETCONTEXT; doc =This leaf function sets the ENCLAVECONTEXT field in SECS.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=ETRACKC; doc =This leaf function activates EBLOCK checks.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=FXRSTOR; doc =Restore the x87 FPU, MMX, XMM, and MXCSR register state from m512byte.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=FXRSTOR64; doc =Restore the x87 FPU, MMX, XMM, and MXCSR register state from m512byte.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=FXSAVE; doc =Save the x87 FPU, MMX, XMM, and MXCSR register state to m512byte.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=FXSAVE64; doc =Save the x87 FPU, MMX, XMM, and MXCSR register state to m512byte.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=MASKMOVQ; doc =Selectively write bytes from mm1 to memory location using the byte mask in mm2. The default memory location is specified by DS:DI/EDI/RDI.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=PSHUFW; doc =Shuffle the words in mm2/m64 based on the encoding in imm8 and store the result in mm1.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=RDGSBASE; doc =FSGSBASE
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=STAC; doc =Set the AC flag in the EFLAGS register.
WARNING: parseArch: no arch for str ""
MnemonicStore: CreateAsmSignatureElement: arch is "": mnemonic=WBNOINVD; doc =Write back and do not flush internal caches; initiate writing-back without flushing of external caches.
（I thought it was a setting problem, so I turned on all the options in the plugin settings）。。。。

**Comment by good768** [comment]
EMMM，I solved this problem by overwriting the latest version with the original version of the file other than the server, so that the code color is correct and there is code completion
![image](https://github.com/HJLebbink/asm-dude/assets/64065417/f745a8e2-660c-47f1-b102-3af1b4e28569)
![image](https://github.com/HJLebbink/asm-dude/assets/64065417/2c1c9f28-c9be-41c2-b9ba-b575fcfdf24b)
