### ISSUE TITLE
I can't install asmdude.can  Anyone help me to solve this problem?

### ISSUE THREAD

**Issue by ashikaround** [HJLebbink/asm-dude#153]

**Comment by ashikaround** [comment]
![IMG_20231106_023442.jpg](https://github.com/HJLebbink/asm-dude/assets/149964092/cc3ce249-76eb-4ed2-8012-b82abedbae20)

Always time it shows this massage.

**Comment by HJLebbink** [comment]
You will need to provide some more information, such as what were you trying? If you are trying to install AsmDude (and not AsmDude2): its deprecated, and I wasn't planning to put more time in Microsoft horrible VS2019 to 2022 transition.

**Comment by ashikaround** [comment]
> You will need to provide some more information, such as what were you trying? If you are trying to install AsmDude (and not AsmDude2): its deprecated, and I wasn't planning to put more time in Microsoft horrible VS2019 to 2022 transition.

Thanks for replying to me....I solved this problem .. I  installed asmdude2 and it's working now. Thank you again
