### ISSUE TITLE
Warnings get duplicated in the Error List when closing/reopening files.

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#16]
Steps to reproduce:

- Add a file to your solution that causes an "Undefined Label" warning.
- Close and reopen the file multiple times.

Visual Studio's Error List will continuously add the same warning.  The only way I can find for clearing the Error List is closing and reopening Visual Studio, which feels like a subpar solution.

Same thing happens with the "Is the Tools>Options>AsmDude options pane not visible?" message.  Continuously gets duplicated in the Error List until you close Visual Studio.

**Comment by HJLebbink** [comment]
Somehow the LabelGraph is not disposed properly. I'll look into it.

**Comment by HJLebbink** [comment]
Fixed the duplicates (by making the ErrorTaskList part of a proper Singleton). However, if you close the document, the warnings are not removed from the TaskWindow which would have been the best solution. Version after 1.5.1.1 will have this fixed
