### ISSUE TITLE
seprate assemblers and there keywords

### ISSUE THREAD

**Issue by sajadbanooie** [HJLebbink/asm-dude#17]
there should be an option in the option menu which will specifies the assembler.
MASM keywords should not be in autocomplete menu if the assembler is NASM and they should not be highlighted.

**Comment by HJLebbink** [comment]
Yes, I wanted to have such functionally for a while. A next version will sport such an assembler option. If you happen to have a list of NASM keywords with descriptions, that would speed up things.

**Comment by sajadbanooie** [comment]
you can read nasms [doc](http://www.nasm.us/doc/nasmdoc3.html).
