### ISSUE TITLE
Workaround for labels defined in "parent" include file?

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#18]
Similar to #15 but inversed:

### a.asm

    include "a.inc"
    
    segment_name SEGMENT USE64
        on_fail:
        hlt
    segment_name ENDS

### a.inc

    inc_segment_name SEGMENT USE64
        jmp on_fail
    inc_segment_name ENDS

I'm guessing the change you made for #15 was just to recurse down include directives when you saw them.  This seems a lot trickier as there's no clues where "a.inc" was included into.

**Comment by Tinister** [comment]
I'm wondering if the best way to do this is read all of the .asm and .inc files that were added to the solution and use that as the label graph.  If a label is defined in a different file in the solution then great, call it a defined label (even if those two files may not end up together when the assembler starts doing includes).

I wouldn't do label clash checking that way, though.  Current behavior for that is fine.

**Comment by HJLebbink** [comment]
Yes, initially I was also considering one label graph for all files in the solution. However, I haven't found a way to make these graphs incrementally, and update an existing graph based on buffer changes. At the moment every file has its own label graph which is recomputed after its buffer is chanced. Not ideal but it is acceptable for files smaller than 10K lines. Once I've figured out how to make incremental updates I can build such a superior solution. I'll put in on the todo list.
