### ISSUE TITLE
Changing highlight colors

### ISSUE THREAD

**Issue by russtone** [HJLebbink/asm-dude#2]
Is it possible to change highlight colors? I'm using dark visual studio theme and current colors don't look nice with this theme.
![asm](https://cloud.githubusercontent.com/assets/3396041/13388548/e63b6e46-ded1-11e5-99d7-cfdd01c2bffe.PNG)

**Comment by HJLebbink** [comment]
Hi Anton,

Good point, didn't think about that. I'll try to make that configurable in
an options page by the end of the week.

Regards!

**Comment by russtone** [comment]
It would be great. Nice plugin indeed)

**Comment by HJLebbink** [comment]
Version 1.4.0 allows customizing the highlight colors. See Tools>Options>AsmDude>Syntax Highlighting.
