### ISSUE TITLE
Allow configuration or override for disabling label warnings.

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#21]
In cases where "undefined label" or "label clash" warnings occur where it's too complex to fix or to modify AsmDude to support that usage.

I'm thinking either or both:

- A Tools -> Options -> AsmDude setting for disabling the label checking solution-wide.
- Some sort of `#pragma`-like syntax.

Possible syntax:

     ; pragma AsmDude warning disable
     jmp undefined_label
     ; pragma AsmDude warning restore

**Comment by HJLebbink** [comment]
Yes, this is something I would love to add, although I have no idea how to track which pragma is supposed to disable which warning. I'll put it on the TODO list
