### ISSUE TITLE
Support for MASM Comment Directive

### ISSUE THREAD

**Issue by TacticalMook** [HJLebbink/asm-dude#22]
Example:
```
comment ! [this line is commented]
	[multiline comments]
	[any symbol can be used as a delimiter, first instance of this symbol marks the end of the comment directive]
! [this line is also commented]
```
MSDN documentation: https://msdn.microsoft.com/en-us/library/4c9h3x38.aspx

**Comment by HJLebbink** [comment]
I always wondered why it was necessary to have such a strong method in which any char could be redefined. It makes it hard to make a clean parser/tagger, let alone an efficient one. I guess that in the future I'll make a separate parser for Masm and another for Nasm. Once I've done that I will consider adding support for the "comment" keyword. I've added it to the TODO list.

For the moment, '#' and ';' give line comments.
