### ISSUE TITLE
Adjusting Syntax Highlighting Requires Multiple Restarts VS2015

### ISSUE THREAD

**Issue by profess** [HJLebbink/asm-dude#26]
Steps to reproduce:
1. From Tools>Options>AsmDude>Syntax Highlighting make a change to one of the colors.
2. Click on OK to confirm the changes.
3. Restart VS2015 to effect the change.
4. Open an ASM project and note that the updated syntax highlighting has not taken effect.

Typical workaround involves disabling the plugin, restarting VS2015, enabling the plugin, and finally restarting VS2015, version 14.0.25421.03 Update 3.

Other than that I'm absolutely loving this plug-in. Thank you for taking the time to develop it!

**Comment by profess** [comment]
Sorry, I see this is a duplicate of the open bug already.

**Comment by HJLebbink** [comment]
Hi Profess,

Yes, I'm still trying to fix this annoying update bug. I've wasted way to much time that could have been spend on useful things such as code completion templates. In a few minutes I'll update the other thread with a possible solution.
