### ISSUE TITLE
Menu doesn't scale with font

### ISSUE THREAD

**Issue by whynot123** [HJLebbink/asm-dude#27]
Visual Studio Pro 2015. check out the screen:
![image](https://cloud.githubusercontent.com/assets/11711568/16875568/cee462b4-4aa8-11e6-8c74-11c7052628bb.png)

**Comment by HJLebbink** [comment]
How did you increase the font size?

**Comment by whynot123** [comment]
Tools->Options->Environment->Fonts and Colors -> Environment Font

**Comment by HJLebbink** [comment]
This is fixed in the next version (after 1.6.0.1). It is not very beautiful, but the font now scales as one would expect.

**Comment by whynot123** [comment]
great stuff! can you advise on how to do clean reinstall? i try uninstalling via Tools -> Extensions and Updates, but it seems to keep configs somewhere, since the colors, etc remain after reinstall

**Comment by HJLebbink** [comment]
Sadly Visual Studio does a horrible job when uninstalling extensions. I use regedit to remove registry keys by hand. I remove all keys that are found when searching for AsmDude. Dangerous indeed. If you come across a better method, do let me know.

**Comment by whynot123** [comment]
it's a shame :)  i tried searching and removing anything with 'asmdude' on c: and in registry, still the colors and settings remain when i reinstall:
![image](https://cloud.githubusercontent.com/assets/11711568/16927964/e2d38aa6-4d38-11e6-97bb-e4cb45b8cdce.png)
![image](https://cloud.githubusercontent.com/assets/11711568/16928044/3e68cbe2-4d39-11e6-9b90-740742b7775c.png)

also, any way to customize gray tooltip font?
