### ISSUE TITLE
QuickInfo tooltips do not scale with editor text

### ISSUE THREAD

**Issue by whynot123** [HJLebbink/asm-dude#28]
Visual Studio Pro 2015. check out the screen:
![image](https://cloud.githubusercontent.com/assets/11711568/16875664/40b4c6ae-4aa9-11e6-8f23-39b71af1e34e.png)
also, general ability to customize font styles/sizes would be great :)

**Comment by HJLebbink** [comment]
That is indeed ugly! I'll look into it shortly.

**Comment by whynot123** [comment]
many thx! there's a setting in Tools->Options->Environment->Fonts and colors->Editor Tooltip
that sets tooltip font style, maybe should inherit from that

**Comment by HJLebbink** [comment]
I haven't found a way to get the used font size yet, and posted a SO question [here](http://stackoverflow.com/questions/38399845/how-do-you-retrieve-the-font-size-of-the-text-editor-in-a-vs-extension).

**Comment by HJLebbink** [comment]
This is fixed in the next version (after 1.6.0.1)
