### ISSUE TITLE
Small highlighting issues

### ISSUE THREAD

**Issue by russtone** [HJLebbink/asm-dude#3]
1) Comment is not highlighted if it appears in line after any numeric constant:
![1](https://cloud.githubusercontent.com/assets/3396041/13522569/4710132a-e201-11e5-8341-5c93c37667dd.PNG)

2) Only first numeric constant in line is highlighted:
![2](https://cloud.githubusercontent.com/assets/3396041/13522518/1ab4d3d8-e201-11e5-9314-47e235bceaa0.PNG)

I am using last version of plugin builded from source

**Comment by HJLebbink** [comment]
Thanx for reporting this. I'll look into it.

**Comment by HJLebbink** [comment]
Fixed bug: after constant no syntax highlighting. Versions after 1.4.0 will have this fix.
