### ISSUE TITLE
error MSB3325 (build error @asm-tools-lib)

### ISSUE THREAD

**Issue by c0ca1ne** [HJLebbink/asm-dude#30]
```
error MSB3325: Cannot import the following key file: AsmToolsListKeyFile.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_ABEED75BFE1F832A
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): error MSB3321: Importing key file "AsmToolsListKeyFile.pfx" was canceled.
```

I am tried 
`sn.exe -i C:\Users\Lee\Source\Repos\asm-dude\VS\CSHARP\asm-tools-lib\AsmToolsListKeyFile.pfx VS_KEY_ABEED75BFE1F832A` and this doesn't work. 

Any help?

**Comment by c0ca1ne** [comment]
I'm disable signing. It is solve this problem?

**Comment by HJLebbink** [comment]
Yes, please disable signing. I don't think it adds any useful functionality, it only adds more points of failure.    I'll disable it in the next version.

**Comment by c0ca1ne** [comment]
No problem 👍

**Comment by plaza-gregg** [comment]
https://net-daniel.github.io/rollupjs785/ The solution popped up
