### ISSUE TITLE
Bug- Code Folding

### ISSUE THREAD

**Issue by Ahmed-YehiaGPEL** [HJLebbink/asm-dude#33]
When I try to use the **#region** keyword and the **#endregion** the code folds properly, when building it won't build producing an invalid character build-fail error at the line of **#region**. 

Note:
**_It was working fine but suddenly it stopped, I tried enabling and disabling the code folding but it didn't solve the issue**_

Thank You

**Comment by HJLebbink** [comment]
Hi Ahmed,

In Masm i use the folding keywords in a remark, for example ";#region". Not sure why it used to work but stopped working, maybe the code has redefined the remark character.

Let me know if this helps.

**Comment by Ahmed-YehiaGPEL** [comment]
Hello H,
Yes it's working fine now, thanks.
I maybe have missed the remark.

Is it possible to completely uninstall and reinstall the tool again, I'm experiencing an error on startup here is  a part of the activity log:

> System.InvalidOperationException: The calling thread must be STA, because many UI components require this.&#x000D;&#x000A;   at System.Windows.Input.InputManager..ctor()&#x000D;&#x000A;   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()&#x000D;&#x000A;   at ....

I'm currently experiencing connection problems so I'm unable to attach the activity log right now but the main problems are linked with the **CodeFoldingTagger.cs** at **line 148** and **CodeFoldingTagger.cs** **line 144**

***I guess this error produced when I tried changing the folding settings, is it possible to reset them?***

Thank You.

**Comment by HJLebbink** [comment]
@Ahmed-YehiaGPEL, I've tried to solve the threading issue you mentioned above, but I can't reproduce it. Were there any specific circumstances, such as, 100k lines in the folding region, 10 levels deep folding regions, a system under very heavy load, less than 4k of free memory, etc. Have you experienced this more than once?

Regards HJ!

**Comment by Ahmed-YehiaGPEL** [comment]
@HJLebbink, No there weren't any special circumstances that would produce the bug, I've just turned of and on the folding ability and changed some settings in the ASM Dude configuration that has no relation to the code folding.
But the file contained lots of code folding, it was about 800 Lines of code, but the folding didn't exceed 100 lines.

Thank you,
A.Y
