### ISSUE TITLE
included files are not scanned

### ISSUE THREAD

**Issue by Sherry-Ashraf** [HJLebbink/asm-dude#36]
![capture1](https://cloud.githubusercontent.com/assets/20145138/21277885/1a28ba48-c3e1-11e6-933a-d8f1192d6650.PNG)

why is there a warning regarding openInputfile and such ?
the extension was working perfectly but suddenly it acted like this!
even thought the code runs successfully

P.s. : when i disable the extension the warning is gone

**Comment by HJLebbink** [comment]
Hi,

AsmDude parses your file and searches for a definition for OpenInputFile, but couldn't find one, hence the error message. You can disable this by unchecking "show undefined labels in error task" and "Decorate undefined labels" in Tools>Options>AsmDude. 

How did you define the memory operand OpenInputFile?

**Comment by Sherry-Ashraf** [comment]
it's not an operand
it's a procedure in irvine32 library and it's working fine
AsmDude just SUDDENLY decided it is undefined!!

actually AsmDude auto-completed them before but now they are undefined!!!
the same goes for Crlf, writeChar, WriteDec, etc...

**Comment by HJLebbink** [comment]
What version of AsmDude are you using. You must be including a file in which OpenInputFile is defined otherwise no assembler knows which memory offset to call. Are you sure you can assemble your file?

**Comment by Sherry-Ashraf** [comment]
last version
yes it assembles and runs successfully and the output is correct

**Comment by HJLebbink** [comment]
is that 1.7.2.6?

**Comment by Sherry-Ashraf** [comment]
1.7.2.5
there's no .6

**Comment by HJLebbink** [comment]
Yes, something seems to go wrong with VS2017, I'll look into it.

**Comment by HJLebbink** [comment]
Hi @Sherry-Ashraf, 

Version 2.7.2.7 will correctly tokenize included files. Thanks for reporting this.

**Comment by Sherry-Ashraf** [comment]
no problem ^_^
it's fixed now
great work  
but it displays label clash warnings regarding the included file (it's a built-in file)
it's a warning  so it's not a big deal but i thought you should know  :)
