### ISSUE TITLE
Highlight colors are not saved in VS2015

### ISSUE THREAD

**Issue by adigostin** [HJLebbink/asm-dude#37]
See the attached image. I changed a few highlight colors, but the Asm Dude plugin ignores them and uses the predefined colors instead. Restarting VS doesn't help.
(I have v1.7.3.2 on VS2015.)
![highlight](https://cloud.githubusercontent.com/assets/7842314/21589981/24bf2894-d100-11e6-9a8d-7fc0c5fe0110.png)

**Comment by adigostin** [comment]
Turns out Asm Dude keeps two sets of colors for highlighting:
- one in the "AsmDude" page of the Options dialog (as far as I can tell these colors are ignored).
- one in the Environment -> Fonts and Colors page (these are actually used).
Why the unused colors?
And how can I make the font *not* italic?

**Comment by adigostin** [comment]
I can't tell when this was introduced. I just installed the addon.

**Comment by HJLebbink** [comment]
You will need to restart VS for these changes to be picked up. Have you restarted VS?

**Comment by adigostin** [comment]
Yes, I had restarted it. No effect.
I just tried again with a new color that I configured in Options -> AsmDude -> General. When I closed the dialog with "OK" it asked for a restart. I restarted VS and again the color I had just set it ignored. The colors actually used are those in Options -> Environment -> Fonts and Color -> Display Items -> AsmDude-XXX.

**Comment by HJLebbink** [comment]
You are right, VS2015 does not save the these options to the properties you mentioned (Options -> Environment -> Fonts and Color -> Display Items -> AsmDude-XXX). VS2017 works fine. For the time being you could edit the AsmDude-XXX values.

**Comment by HJLebbink** [comment]
@adigostin, I've release a new version (1.7.3.5) in which I cannot reproduce the issue in which the colours are not saved. 

Could you please try this new version and check whether you still have that problem in VS2015.

**Comment by adigostin** [comment]
I'm not sure what you changed in 1.7.3.5, cause the issue seems to still be there. See the screenshot below; that's after a VS restart.
What *has* changed in 1.7.3.5 (i.m.o. for the better) is the font, which used to be italic and now it's not.

(Why not remove those color settings altogether? The  AsmDude-XXX colors seem to do the job well.)

![highlight](https://cloud.githubusercontent.com/assets/7842314/21609132/50235072-d1c9-11e6-8912-50eda3a05d9c.png)

**Comment by HJLebbink** [comment]
I'll need to check this on a fresh machine.

**Comment by francescogomez** [comment]
In my PC change color directive work.

**Comment by HJLebbink** [comment]
@francescogomez Do you use VS2015 or VS2017 RC?

**Comment by francescogomez** [comment]
@HJLebbink VS2017 RC

**Comment by lazerzes** [comment]
Was looking into this bug. I uninstalled ASMDude and reinstalled it. Colors updated to the preferences I wanted.

**Comment by HJLebbink** [comment]
@lazerzes To help me reproduce this, which version of AsmDude and VS did you use? Did you download an installer (from GitHub) or did you use the extension installer embedded in VS?

**Comment by lazerzes** [comment]
Using VS2015(w/ Update 3 idk if that matters.)

I used the Marketplace link with version 1.7.3.10 of AsmDude.
I have duplicated it on multiple machines at this point as well.

**Comment by David-Reguera-Garcia-Dreg** [comment]
I have the same problem with colours with VS 2015:

![confirmed](https://cloud.githubusercontent.com/assets/9882181/25037080/62da24fc-20f7-11e7-8b8e-3c8f1b5b8c7f.png)

**Comment by stonedreamforest** [comment]
I have the same problem

**Comment by theawkwardchild** [comment]
I just installed v1.9.2.0 of asm-dude from Visual Studio Marketplace running on VS2017 15.3.4 and I am also experiencing colors not being saved. Other settings are saving such as I turned off Keyword Highlighting for Backgound and Border but could not get the colors to change.

**Comment by stonedreamforest** [comment]
and vs 2017 15.5.0

**Comment by HJLebbink** [comment]
I'm (still) working on a fix. (You could add a bounty to this question, I may help... https://stackoverflow.com/questions/47956223/how-to-change-a-classificationformatdefinition) 

@stonedreamforest and @artemisart I you have a color scheme that works for both the dark theme and the regular theme, I will make it the default.

**Comment by HJLebbink** [comment]
Hopefully fixed this bug in version 1.9.3.6. MEF components are cached and only refreshed when windows is restarted, and not always when VS is restarted. The bugfix is flushing this cache. Hopefully this has fixed your bug, it at least has fixed it for me, for the moment...
