### ISSUE TITLE
Incorrect undefined label warnings in MASM procedures

### ISSUE THREAD

**Issue by slivermeteor** [HJLebbink/asm-dude#38]
Look at the screenshot.
![image](https://cloud.githubusercontent.com/assets/20829599/22135054/b374a690-df06-11e6-9483-eccf8ec71ce9.png)
the LookupAPI Lable can't be identified correctly in mian procedure.

**Comment by HJLebbink** [comment]
Yes, I see, that is indeed an annoying bug. I can't resolve that in 20 min, with a bit of luck I can fix that in the weekend.

**Comment by slivermeteor** [comment]
Waiting for your good news :)

**Comment by francescogomez** [comment]
@slivermeteor maybe need help for @HJLebbink ?

**Comment by HJLebbink** [comment]
Could you please check whether version 1.7.3.6 solves your issue.

**Comment by slivermeteor** [comment]
Yeah,I have been using the new version.It seems solves the old issue because there is no warnings in the procedure.But another problem that the all highlight are out of action happened.
![image](https://cloud.githubusercontent.com/assets/20829599/22210632/758a78b6-e1c5-11e6-8119-993ca3f12eb9.png)
After founding the new issue, I reinstall the old version(1.7.3.5).In this version, everything works fine except the old issuse.So I believe the failure phenomenon is a new issuse of the new version(1.7.3.6).

**Comment by HJLebbink** [comment]
Hi @slivermeteor, could you explain the phrase "But another problem that the all highlight are out of action happened." means. What version of VS are you using?

**Comment by HJLebbink** [comment]
Ah, I see, somehow things break down in VS2015, probably in an include (from VS2017) that is not compatible with VS2015. Shitty VS, I guess I'll have to waste some extra time on nothing...

**Comment by HJLebbink** [comment]
Fixed in version 1.7.3.8
