### ISSUE TITLE
Incorrect Code Folding for extern proc in MASM

### ISSUE THREAD

**Issue by francescogomez** [HJLebbink/asm-dude#39]
See this gif.

![](http://i89.fastpic.ru/big/2017/0125/5b/c08e7df7548df1f5c96e8746a99d0a5b.gif)

**Comment by HJLebbink** [comment]
That is a nice find! I've no idea why this happens. I'll look into it.

**Comment by francescogomez** [comment]
@HJLebbink maybe need building AST and use antlr for this? :?

**Comment by HJLebbink** [comment]
@francescogomez I once considered Irony (https://irony.codeplex.com/) to build an grammar, but I've failed. I've forgot why but I assume that the MASM (and NASM) syntax (with all their fancy stuff) could not be written in an LALR parser. At the moment I don't have time to investigate that further. 

For the bug, that is solvable, probably a buffer that is updated but not listened to.

**Comment by HJLebbink** [comment]
Fixed in the next version after 1.7.3.8
