### ISSUE TITLE
VS2015 Crashed due to System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by iccfish** [HJLebbink/asm-dude#4]
Upgraded to 1.4.2 and open a c# project makes VS2015 crashed.

Visual Studio 2015 Update2 CTP
With Resharper & Code for Roslyn installed.

**Exception info:**
Unhandled exception:
System.Runtime.InteropServices.COMException
The application called an interface That was marshalled for a different thread.  (Exception from HRESULT:0x8001010E (RPC_E_WRONG_THREAD))
   在 Microsoft.VisualStudio.Shell.Interop.IVsThreadedWaitDialog3.StartWaitDialogWithCallback(String szWaitCaption, String szWaitMessage, String szProgressText, Object varStatusBmpAnim, String szStatusBarText, Boolean fIsCancelable, Int32 iDelayToShowDialog, Boolean fShowProgress, Int32 iTotalSteps, Int32 iCurrentStep, IVsThreadedWaitDialogCallback pCallback)
   在 Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitContext.CreateDialog(IVsThreadedWaitDialogFactory dialogFactory)
   在 Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitContext..ctor(IGlobalOperationNotificationService notificationService, IVsThreadedWaitDialogFactory dialogFactory, String title, String message, Boolean allowCancel)
   在 Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.StartWait(String title, String message, Boolean allowCancel)
   在 Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Action`1 action)
   在 Microsoft.CodeAnalysis.Editor.Implementation.TextStructureNavigation.AbstractTextStructureNavigatorProvider.TextStructureNavigator.GetExtentOfWord(SnapshotPoint currentPosition)
   在 AsmDude.HighlightWord.HighlightWordTagger.UpdateWordAdornments(Object threadContext)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Full log was too long to paste here, so I attached it as an attachment.

[fulllog.txt](https://github.com/HJLebbink/asm-dude/files/161754/fulllog.txt)

**Comment by HJLebbink** [comment]
Thank you for reporting this issue. I'll investigate why the HighlightWordTagger gets called from a different thread, and trashes visual studio. Currently I can't reproduce this bug.

Question: Did version 1.4.0 work fine with your setup (Visual Studio 2015 Update2 CTP, Resharper & Code for Roslyn). The only change I've made wrt the HighlightWordTagger is that it lives in a different namespace.

**Comment by HJLebbink** [comment]
Could you please try v1.4.3 and report back whether your problems are resolved. Regards!

**Comment by iccfish** [comment]
1.4.3 does fixed this issue. Thanks! :+1:
