### ISSUE TITLE
Asm syntax highlighting not working in Visual Studio 2015

### ISSUE THREAD

**Issue by justinshapiro** [HJLebbink/asm-dude#43]
I've installed AsmDude through the Visual Studio marketplace. I restarted my computer and tried editing a .asm file, but the syntax highlighting is not showing.

![image](https://cloud.githubusercontent.com/assets/14143046/22845998/9c5f2c44-efa2-11e6-8b60-6c5e634d6e94.png)

I've gone to Tools -> Options -> AsmDude and it says that sytax highlighting is enabled.

![image](https://cloud.githubusercontent.com/assets/14143046/22846013/afc12ad0-efa2-11e6-8eaa-3d74088cfd8a.png)

Why can't I get the syntax highlighting working?

**Comment by HJLebbink** [comment]
Is the Intellisense stuff such as signature help and code completion functioning normally? I've seen this on fresh installs, could not find what the cause was. The mundane windows 'solutions' sometimes seemed to fix it: reboot, reinstall plugin, etc. If you keep this error, or if you fix it and know what caused it, let met know.

**Comment by HJLebbink** [comment]
Where did the error squirrels come from in you screenshot? have you associated an other editor with an .asm file?

**Comment by justinshapiro** [comment]
Yes everything is compiling and working normally. The error squirrels are probably coming from the fact that it's setup at a Visual C++ project. There's no "asm" project option. I've tried rebooting, reinstalling, etc. Nothing is working.

**Comment by HJLebbink** [comment]
Tools > Options > TextEditor > FileExtensions. Have you associated extension .asm to an editor? If you have done that AsmDude can't take control over files with the .asm extension.

**Comment by justinshapiro** [comment]
Yes, and removing that worked! For some reason when I removed it did that the first time it did not do the trick and just got re-added in somehow. I actually had to create a new project for the association to clear. Now everything is working great. Thanks!
