### ISSUE TITLE
Feature request: Add "Font Color" option under "Keyword Highlighting"

### ISSUE THREAD

**Issue by SeanPesce** [HJLebbink/asm-dude#44]
Currently there is only an option to customize the background color for keyword highlighting. Due to the inability to customize the **font** color for highlighted keywords, this can make it difficult to read highlighted keywords when using certain color schemes (as seen in the picture below).  

![image](https://cloud.githubusercontent.com/assets/20076909/24432893/0ec63ec0-13f3-11e7-9a86-62cb54109e9e.png)

I'm requesting the addition of a "Font Color" customizer in the "Keyword Highlighting" section of the AsmDude plugin options, as seen in the following picture (and marked with a red arrow):  
  
![image](https://cloud.githubusercontent.com/assets/20076909/24432830/b8ad6374-13f2-11e7-803e-5d5be07d163c.png)  
  
To make the feature extra convenient, I think it would be best to also include an "Inherit color" option for the highlighted keyword font color. This (default?) option would leave the font color of highlighted keywords unchanged from the normal font color used by the current color scheme.

**Comment by HJLebbink** [comment]
Yes indeed, this is a rather annoying, it will take a bit more time to fix this.

I'm working on it.

See also [this question on msdn](https://social.msdn.microsoft.com/Forums/vstudio/en-US/803a8d90-3444-41d0-b900-d2fd5ffa4aee/change-the-foregroundcolor-with-a-markerformatdefinition?forum=vsx#803a8d90-3444-41d0-b900-d2fd5ffa4aee)

**Comment by HJLebbink** [comment]
It seems impossible to change the text color with MarkerFormatDefinition (the infrastructure I use to implement keyword highlighting). What can be done is change the background color and the border color. In the next version (after 1.7.4.0) both background color and border color can be changed in the AsmDude options page. In the dark theme you can switch off the background color while keeping the border color and things should remain readable.

Hope this helps, I'll release it in a few hours.
