### ISSUE TITLE
labels not behaving properly in 1.7.5.1

### ISSUE THREAD

**Issue by quasar66** [HJLebbink/asm-dude#46]
Hi..
As explained, the labels are getting marked as missing. Am attaching a zip of a small sample project that reflects this label issue.
Platform = VS2017 on Windows 10 pro 14393.1066 running on i7 4770K
ASMDude version = 1.7.5.1
Details in the image attached.

![asm_prob](https://cloud.githubusercontent.com/assets/27453389/25026807/624c499c-2076-11e7-85dc-be0620142829.PNG)

**Comment by HJLebbink** [comment]
Aha, I wasn't aware that a white space between label identifier and the following semicolon was valid in MASM. If you remove the white space it works as intended. I'll check if it isn't too much work to allow a space there, but must say that I hadn't seen such a space been used there before. 

I'll ask the AsmDude team if he has some time left this weekend...
