### ISSUE TITLE
Location of Grey Suggestion popups-and other comments

### ISSUE THREAD

**Issue by dwkrueger2** [HJLebbink/asm-dude#49]
1. The little pop ups as you hang a cursor over them are great.  But they are in the way too often.  Consider putting the offset of the label above the current line of code.  I suspect everyone is looking downward in the document anyway.  I think that is consistent with other MS Popups.  

2. Constants such as  'COURSE EQU <"CS 271 Winter 2017 Section 400  ">'  which occur before the .data segment have 'LABEL' listed as their type in the suggestion popup.  This incorrect as these are precompiler directives

3. If there is no documentation site consider just adding a folder to the GitHub where we can add documentation.  I'm really quite new to this github repository but have some familiarity with CVS and have read the gitbook.  So maybe my suggestion is not the best location but I think you should understand the intent.

4. It would nice if user-defined types were highlighted. 

5. The keyword highlighting kinda grabbed single characters, this was annoying because single quotes and double quotes were being grabbed.  I think it would be better if keyword highlighting was limited to words that matched keyword requirements of assembly.  I just turned it off.  

6. Of course the universe of features in infinite. Still if I may suggest one small feature,  If included library can be scanned for available procedures that would be nice to have those highlighted not marked as invalid, and perhaps a hover tooltip made to show where the source of the highlighting comes from.
For Example:  INCLUDE Irvine32.inc  has procedure WriteString.  ASM-Dude currently marks it as invalid (because it doesn't know about objects from the linking).  Maybe as a simple work around the Irvine32.lib procedures could just be added to list of words and an option put in the settings.

7. I'm in my first assembly class so I hope that my comments are appropriate.

**Comment by HJLebbink** [comment]
Thanx for the remarks:

1] The QuickInfo popups are handled by Visual Studio and are indeed often in the way, and they have someother additional issues (such as flickering when the popup cannot be fit, you cannot copy paste its content). The VS API does not provide placement hints. There is little I can do.

2] Yes, symbolic names such as your COURSE are not labels, I grouped them with symbolic labels (which are almost identical I guess). I'll see if I can update the naming.

3] Do you mean a github wiki? I've added it (its between projects and pulse) I haven't used it, and don't know if it's useful.

4] Assembly language is a badly structured language, horrible to parse, no wonder people moved on to Fortran and Cobol. If I could parse those types nicely, highlighting will be simple, I'll put it on the TODO list.

5] Keyword highlighting regards strings as one word as defined by how labels may be formed. For example, my Fortran compiler spits out code with these illegible labels:
`lea rcx, OFFSET FLAT:??_C@_0FE@OJFGMKFJ@ERROR?3?5dataset?3?3HexDataSet?3?3getV@`, these labels are one word. I use this tool to understand assembly code.

What I could change is if you select a single 9, the 9 in register r9 is not highlighted, which is somewhat annoying, but I haven't had time to fix it.

6] Yes, this is supposed to work, I'll fix this.

7] No worries.
