### ISSUE TITLE
Files are not included with INCLUDE

### ISSUE THREAD

**Issue by dwkrueger2** [HJLebbink/asm-dude#50]
I was told this was supposed to be working and start a new issue here.

INCLUDE Irvine32.inc
TERMMSG	 EQU < "(Press ENTER to Terminate)">
.data
; Prompts    
     prompt_Welcome	    BYTE		WELCOMEMSG , 0	
.code   
main PROC
    ; Press Enter to Terminate
    mov	  edx, OFFSET prompt_goodBy 
    call	  WriteString ; <-- Irvine Library Call
    call	  ReadInt  ; <-- Irvine Library Call
    call	  CrLf; <-- Irvine Library Call
   exit 

main ENDP

![image](https://cloud.githubusercontent.com/assets/28245241/25622661/1734911a-2f23-11e7-8fd3-5a4e54344bf3.png)

You can see there is a red squiggly line under WriteString, ReadInt, and CrLf

**Comment by HJLebbink** [comment]
If the file Irvine32.inc is in the same directory as your source file, it ought to work. Putting the filename between quotes as in "Irvine32.inc" should also works, the capitals also do not matter, IRVINE32.INC should also work. 

Most likely you have instructed MASM to resolve includes from a directory, this information is not available to AsmDude, it just crawls your files and recursively includes files. It simply cannot find your file.

You will have to add a relative path (absolute paths do not work), eg,
`INCLUDE "..\somedir\irvine32.inc" `

Hope this helps
