### ISSUE TITLE
#region / #endregion directives not recognized

### ISSUE THREAD

**Issue by dwkrueger2** [HJLebbink/asm-dude#51]
I'm pretty sure this is an asm-dude glitch... I hunted all over the internet for these preprocessor directives and it looks like it's linked to the type of editor (i.e. c# or C++)  so when no editor base is chosen then it doesn't recognize the caracter... (i.e. I don't think they are stripped out prior to compiling)

![image](https://cloud.githubusercontent.com/assets/28245241/25759662/730a9428-31a1-11e7-86bc-1b3f44b6ba36.png)

**Comment by dwkrueger2** [comment]
Nevermind I found the response in the closed issues

**Comment by dwkrueger2** [comment]
Code folding in MASM requires the directive to be commented out prior to inlining.  (Might want to put this in the tool tip on the options for users)

**Comment by HJLebbink** [comment]
Yes, good idea, done that!
