### ISSUE TITLE
Comments are always italic

### ISSUE THREAD

**Issue by JohanKAdams** [HJLebbink/asm-dude#52]
[As we all know](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/2840449-editor-support-for-italics-fonts-syntax-highlighti), Visual Studio does not support setting any syntax highlighting explicitly to italic or non-italic.

As this extension sets all comments to italic, I kindly request the option to let the user decide whether he wants his comments to be displayed in italics or not:

![comment](https://cloud.githubusercontent.com/assets/29004367/26523432/255ee086-4320-11e7-8a37-92313caf7efa.png)

**Comment by HJLebbink** [comment]
The next version (after 1.8.0.0) will have an checkbox for italic remarks. 

Out of curiosity, why do you need non italic remarks?

**Comment by JohanKAdams** [comment]
> Out of curiosity, why do you need non italic remarks?

Purely out of personal preference. My other C/C++ code uses non-italic comments, so I prefer my Assembler remarks also to be non-italic. :)
