### ISSUE TITLE
Tooltips use wrong colors

### ISSUE THREAD

**Issue by JohanKAdams** [HJLebbink/asm-dude#53]
The tooltips always use the default colors (e.g. orange), not the colors from Visual Studio's Fonts and Colors option menu (e.g. green):

![tooltip](https://cloud.githubusercontent.com/assets/29004367/26523457/9fc79f8e-4320-11e7-9d1d-b17b108bb104.png)

**Comment by HJLebbink** [comment]
Does this also happen if you go to Tools>Options>Environment>Fonts and Colors>AsmDude-SyntaxHighlighting-Label and set item foreground to default. And set the color you like the label to have in Tools>Options>AsmDude>Label. 

The coloring in the QuickInfo tooltips uses the colors as set in AsmDude options, and not the colors if you happen to have override them in VS

**Comment by JohanKAdams** [comment]
Thanks for your reply.

I had to set both the settings in Tools>Options>Environment>Fonts and Colors as well as as the settings in Tools>Options>AsmDude>Label to my desired colors.

Now all tooltip colors are as expected, except for jumps:

![tooltip-2](https://cloud.githubusercontent.com/assets/29004367/26529711/be6b5b44-43cd-11e7-9551-d5b14310700a.png)

For jumps the tooltip shows "Mnemonic" and uses the mnemonic color. This probably has to do with the following `switch`-statement:

https://github.com/HJLebbink/asm-dude/blob/master/VS/CSHARP/asm-dude-vsix/QuickInfo/AsmQuickInfoSource.cs#L193-L194

**Comment by HJLebbink** [comment]
Yes, makes sense. Next version (after 1.8.0.0) will have that fixed.
