### ISSUE TITLE
No Highlighting on VS2015 (v1.8.1.1 BROKEN; v1.8.0.0 OK)

### ISSUE THREAD

**Issue by dwkrueger2** [HJLebbink/asm-dude#54]
For some reason my highlighting is gone... I have fiddled around with opening / closing VS with different settings.  I cannot find a file extension that asm is associated with.. so I don't think that is the issue.

I see there was an update a couple days ago..  Is it related?  Next step is to uninstall / re-install the plugin.

**Comment by dwkrueger2** [comment]
Uninstalled / Reinstalled extension... No effect...
I wish I could chase down this bug but I just don't know enough on how these extensions are coded or how they are loaded into VS.

**Comment by HJLebbink** [comment]
have you checked https://github.com/HJLebbink/asm-dude/issues/43

**Comment by dwkrueger2** [comment]
Yes... When I download the source code asm-dude-vsix is not compatible with my current version of VS... Could that be an issue?

**Comment by dwkrueger2** [comment]
It is not a discernable file association issue.

**Comment by dwkrueger2** [comment]
is vsix the extension platform?  like the VS Extension Development items?

**Comment by HJLebbink** [comment]
The source code is c#7, the project is a vs2017 project, but it project creates an installer for vs2015 and vs2017. You are probably using vs2015 and the plugin should work perfectly. Yes vsix is the plugin. 

I have no idea why the .asm file is not associated with the AsmDude extension, which is what probably has happend. Have you upgraded via the Visual Studio or have you downloaded the vsix from github?

**Comment by dwkrueger2** [comment]
I just cloned the repository and tried to open it... I'm upgrading my VS to 2017 now..

**Comment by dwkrueger2** [comment]
dang... went to a new computer and tried to use it without updating... but some how the update automatically got rechecked and when I rebooted my computer it updated the asm-dude extension and lost the syntax highligting..

**Comment by dwkrueger2** [comment]
New Version works in VS Community 2017 though just fine

**Comment by HJLebbink** [comment]
Thanks for the info. I'll check on VS2015 why the 'crosscompile' was messed up (again).

**Comment by Tiiberiu** [comment]
I have the same problem, when I switched from asm to windows C++ then back to asm, the highlight is gone. (VS2015)

**Comment by HJLebbink** [comment]
@Tiiberiu Could you try to revert to 1.8.0.0, (uninstall v1.8.1.1 and download 1.8.0.0 from github) to see whether that solves the issue. In the meantime I will waste some time figuring out why VS2015 complains...

**Comment by Tiiberiu** [comment]
That solved the issue, thanks.

**Comment by HJLebbink** [comment]
I've created a new release v1.8.1.2 that should fix this issue. If someone still has problems, please let me know.
