### ISSUE TITLE
hello Highlight function incomplete in Disassembly windows：）

### ISSUE THREAD

**Issue by stonedreamforest** [HJLebbink/asm-dude#57]
and need hightlight ：

1. register
2. Symbol(function) name
![1](https://user-images.githubusercontent.com/16742566/27250902-44b990d6-536d-11e7-893e-9f840d36d00c.png)

You can refer to [x64dbg](https://github.com/x64dbg/x64dbg)

**Comment by HJLebbink** [comment]
Next version (after 1.8.2.0) will have better syntax highlighting in the the Disassembly window
