### ISSUE TITLE
Using ">" or "<" crashes Visual Studio!

### ISSUE THREAD

**Issue by SpookyVerkauferin** [HJLebbink/asm-dude#59]
Example:
```
IF ax > 1
    add ax, 1
.ENDIF
```
Causes Visual Studio to instantly crash :(

EDIT: As soon as you type ">" or "<" within the editor or load a file with the symbols it crashes VS.

**Comment by HJLebbink** [comment]
Thank you for reporting this. It has been fixed in version 1.9.0.1

**Comment by SpookyVerkauferin** [comment]
Thanks mate! Also great work on AsmDude, I love your work!
