### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by rabbixx** [HJLebbink/asm-dude#6]
JUMP:
This option stays at a dark blue color no matter what I set it to.  The others seem to be working.

MISC:
Doesn't seem to pick up signed data types like. SDWORD, SWORD, etc

Overall really cool project and look forward to seeing how it progresses.  Thanks.

**Comment by HJLebbink** [comment]
Thanx for reporting. The color customization for the jump is fixed and the signed datatypes are added. You can either wait for a next release or compile the sources and use it straight away.
