### ISSUE TITLE
Help tooltip does not close when clicking on disassembly window

### ISSUE THREAD

**Issue by powercode** [HJLebbink/asm-dude#63]
The tool tip window seems to be lingering in the background if it is not closed by the red `x` to the right.
Alt+Tab then shows a visual studio as a mini window of the asmdude tooltip. 

Steps to reproduce:
Hover over asm instruction.
Click in the disassembly window to hide the tooltip.
Press Alt+Tab

![Alt+Tab after loosing tooltip focus](https://user-images.githubusercontent.com/3505151/31827951-406d31dc-b5b9-11e7-95ff-e8c8b10ab269.png)

**Comment by HJLebbink** [comment]
Interesting, I'll investigate it.

**Comment by HJLebbink** [comment]
Next version (after 1.9.3.0) has this bug fixed. Proper housekeeping!
