### ISSUE TITLE
Unable to load asmdude 1.9.3.0 in VS15

### ISSUE THREAD

**Issue by Thremus** [HJLebbink/asm-dude#65]
Except from the vs15 log

Begin package load [AsmDudePackage]

CreateInstance failed for package [AsmDudePackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0,

**Comment by HJLebbink** [comment]
I'll look into it. but I'm a bit disappointed with how VS2015 is supposed to be supported by every VS2017 update.  There always seems to be something broken in either VS15 or VS17.  

Is there a particular reason you use VS15? (I'm considering dropping support for vs15)

**Comment by Thremus** [comment]
No special reason, just my project is still 1on VS15.

**Comment by babadro** [comment]
The same problem. I had to install old version.

**Comment by HJLebbink** [comment]
Thank you for not giving up! 

What I need to do is downgrade all the included libraries to version 14, but MS has decided to have monthly updates and these 14 versions do not work in VS2017 sometimes. I'll check with the current VS versions today!

**Comment by HJLebbink** [comment]
Fixed in v1.9.3.2: VS 2015 support is fixed.
