### ISSUE TITLE
Dark theme highlight suggestions

### ISSUE THREAD

**Issue by stonedreamforest** [HJLebbink/asm-dude#66]
> 
> vs dark theme (foreground-color)r		g   		b: 									
> syntax highlightling - documentation link	:150		85		90	
> syntax highlightling - highlight word		:255		255		255	(background-color)										 
> syntax highlightling - Constant			:128		128		128									 
> syntax highlightling - Directive			:60		150		190	(important)
> syntax highlightling - jump 				:200		180		20
> syntax highlightling - label		 		:20		140		50
> syntax highlightling - label defintion		:60		180		40
> syntax highlightling - misc				:120		220		130
> syntax highlightling - mnemonic			:100		100		120
> syntax highlightling - Register			:190		90		10
> syntax highlightling - remark				:50		130		80

**Comment by HJLebbink** [comment]
Hi Tennn,

Are these defaults sensible only for the dark theme or are they acceptable for both the normal (light) theme **and** the dark theme? If these can be used for both themes I can just make them the default. If they not not usable for the light theme, I'll need to come up with something that values are loaded depending on the theme one is using. I'm not sure whether that is possible. 

I'll look into it.

**Comment by stonedreamforest** [comment]
only for the dark theme.
