### ISSUE TITLE
Creating new data base to microcontroller

### ISSUE THREAD

**Issue by urbanze** [HJLebbink/asm-dude#67]
Hi! I was trying to reconfigure its extension to Visual Studio 2017, causing VS to highlight the Expressions of the ESP32 Microcontroller  (ULP) Assembly.

Here is the mnemonic's and register's: http://esp-idf.readthedocs.io/en/latest/api-guides/ulp_instruction_set.html

I was able to change the registers and guidelines, but it was not perfect, see "NOREG" in highlight box: https://i.imgur.com/mgRmJ0M.png
This is true even with the description of the defined register, see in picture bellow.

The mnemonic's did not work in any of my attempts. I tried changing the 2 SIGNATURE files and even creating a <mnemonic> in asmdudedata, but it also did not work. https://i.imgur.com/NPdMi2r.png

Can you help me or even create highlights for the assembly of that microcontroller? There are few register's and mnemonicos, I did a small part that was not perfect, but the mnemonicos discouraged me :(

**Comment by HJLebbink** [comment]
I'll give it a try tomorrow, I'll let you know.

**Comment by urbanze** [comment]
Thanks for help!!!!!!

I'm sorry, I'm not very familiar with github. My changes were just asmdudedata.xml, as you mentioned in readme. Here is the download link or view of the edition I made: https://drive.google.com/file/d/14Siulf-Ekgoxj0QIE0q5R46qKQ5GEmlt/view

**Comment by HJLebbink** [comment]
If you clone the project I can push changes to your clone that are not compatible with my version. Do play around with GitHub, is not difficult to learn, and rather useful.

**Comment by urbanze** [comment]
I know a little how to use git, but as I installed the direct asmdude of "extensions" in visual studio, I do not know where or what files I should put here, because they are very different from the ones I find here in git.

The file I am editing is a simple .S, before I edited through notepad and then I started using VS.

I will take some files that I find relevant and all the folder of the asmdude and I will put here: https://github.com/urbanze/asm-dude

I clicked "fork" and added the files:
ulp.S
r2yv22b5.yn5.rar (all files from asmdude in my pc (appdata\microsoft\visualstudio...))

**Comment by HJLebbink** [comment]
Interesting experiment. 

Shoot, I forgot that in older versions mnemonics and registers were fully defined in the text file you were editing. And adding, removing or changing did not require one to rebuild the project. In later versions mnemonics and registers moved to hard-coded enumerations for speed considerations, and what remained in a text file ware the descriptions and their signatures.

What I've tried: 

1] Cleared the files "signature-hand-1.txt" and "signature-june2016.txt", the files need to be present, but the content can be removed.

2] Remove everything you don't need in "AsmDudeData.xml". Add mnemonics (instructions) to the miscs group:
`    <miscs>
        <misc name="MOVE" arch="8086">
            <description>Move register</description>
        </misc>
    ...
   </miscs>
`

This way you get syntax highlighting and code completion for these keywords. Sadly, you will not get signature help, label analysis which I hoped would have worked. 

You can also use the group userdefined to get syntax highlighting: 
`   <userdefined>
        <userdefined1 name="R0">
              <description>R0 Register 16bit</description>
        </userdefined1>
       ...
     </userdefined>
`

But it seems code completion does not work for the keywords defined in these groups. I'll fix that somewhere in the future. 

I never thought that it would be sensible not to have 8086 instruction set support, thus it cannot be switched off. So you will get syntax highlighting for these instructions. That is annoying. I may fix that. 

**Conclusion:** You can have syntax highlighting, and code completion, but no label analysis and no signature help.

Let me know if you need help experimenting. I the past I wrote for MicroBlaze which was hell without proper tools.

**Comment by urbanze** [comment]
Thank you for your help! I will give a great tidy up to the mnemonicos and registers to be "less Christmas", and I will probably post in the ESP32 community ...

The only thing that got "bad" is this issue of 8086, that even defining a different WAIT, it stayed with the old, see in the image that is the same as previously editions. Is there anything I can do to remove this easily? Or is it up to you to tinker with the internal files for a new update?
https://i.imgur.com/217of29.png

**Comment by HJLebbink** [comment]
I'll experiment whether I can make the 8086 optional, such that you can switch it off. Hopefully, the 
`<misc name="MOVE" arch="8086">` will still work without the arch label.

**Comment by urbanze** [comment]
I finished editing all the mnemonics and recorders, had to write one by one, gave a JOB! lol

When I copied directly from the site, I realized that some items like typing "R0> = value" generate error by "> =" or similar. Soon I wrote everything in my hand.

I will wait for the correction of these "puple mnemonics" that are 8086, is the only defect that overrides all my manual changes, after that will be perfect!

**Comment by HJLebbink** [comment]
It is slightly more complex than I had hoped for. I never bothered to make sure that instruction sets that are not enabled are also not highlighted. Selected instruction sets only used by code completion and signature help.  I'll need more time to fix this.

**Comment by urbanze** [comment]
The only thing I can tell you about, and what you already know, is that even if you disable all option highlighting options, they continue to appear. If this little button should be very important to work correctly, the problem is corrected. I'll be waiting! Thanks for the attention :D

**Comment by HJLebbink** [comment]
Thanx for waiting. Version 1.9.4.2 does not highlight instructions that are not switched on.
