### ISSUE TITLE
AsmDude crashes on VS2015: ValueTuple not found 

### ISSUE THREAD

**Issue by jeigh** [HJLebbink/asm-dude#69]
OS: Windows 7
VS 2015
I receive this error in my ActivityLog.xml file when loading up an existing asm file.  I have to then use process monitor to kill VS.

System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.   at AsmDude.MasmTokenTagger.<GetTags>d__20.MoveNext()   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
--

**Comment by HJLebbink** [comment]
What version of AsmDude are you using?

**Comment by jeigh** [comment]
Downloaded it streight off the marketplace link just now.   Version 1.9.3.6

**Comment by jeigh** [comment]
I noticed that the project file in your git repo took 4.7 as a dependency.   I installed that on my machine and now no longer get the error message.   I suspect this plugin was not meant to run on vs 2015 unless you install the .net framework 4.7 independently.

**Comment by HJLebbink** [comment]
Thanks for letting me know. Yes .net 4.7 is a prerequisite, I assumed the plugin would not even run when this requirement wasn't met.

**Comment by AnonymousBinaryTrader** [comment]
Why I did get this message?

**Comment by Adam8882000** [comment]
yeah

**Comment by HJLebbink** [comment]
I think Github or your account got hacked in the last 6 hours, and you were added to the watchers of this list

**Comment by CHarrisMedia** [comment]
I was also added and my account has not been hacked.

**Comment by HJLebbink** [comment]
Some hacker probably thought it is funny to add you to a lot of hacker tools.

**Comment by Adam8882000** [comment]
ok let me check

**Comment by Coocla33** [comment]
I have the same problem the fuck

**Comment by MrMcBaggins** [comment]
Same.

**Comment by ParTyzanTR0nin** [comment]
Why u writing on my mail wtf get a room guys


06.01.2018 7:47 PM "Henk-Jan Lebbink" <notifications@github.com> napisał(a):

**Comment by AnonymousBinaryTrader** [comment]
%¤#%¤"%#"&¤%# I just say :(

**Comment by hz3012** [comment]
same problem here can I enable 2fa on github

**Comment by AnonymousBinaryTrader** [comment]
Because I have github account but really not with this email address ...

**Comment by hz3012** [comment]
One thing is confirmed that all hackers are nerds

**Comment by HJLebbink** [comment]
There are 2400+ people added to the watchers of this project, some of you are also added to other disassembly tools, something got hacked already. Just unwatch I guess.

**Comment by AnonymousBinaryTrader** [comment]
Did that & add 2way & changed password :)

**Comment by vasilykolosov** [comment]
Happy holidays guys. Same crap here. Hope I was hacked, been waiting for
this moment for a while now.

**Comment by migueloliveira4002** [comment]
stop

2018-01-06 16:59 GMT-02:00 AnonymousBinaryTrader <notifications@github.com>:

**Comment by lucisx10** [comment]
What the fuck ?

On Sat, Jan 6, 2018 at 8:24 PM, migueloliveira4002 <notifications@github.com

**Comment by alossra** [comment]
WTF by the way Logan is an AS*/" Ho*-/

2018-01-06 19:24 GMT+00:00 migueloliveira4002 <notifications@github.com>:

**Comment by alossra** [comment]
xD

2018-01-06 20:24 GMT+00:00 lucisx10 <notifications@github.com>:

**Comment by alossra** [comment]
please make the world a better place and stop that shit XD

2018-01-06 20:25 GMT+00:00 noredinearbaouivigaso <
noredinearbaouivigaso@gmail.com>:
