### ISSUE TITLE
Entering faulty stuff at the beginning of an asm brings up an NULL object error

### ISSUE THREAD

**Issue by dtr** [HJLebbink/asm-dude#7]
- add an asm file to the project
- enter abcdefghi
- press [Enter]

-> Reference NULL Exception

The simple solution is, not to do that. But the problem is symptomatic to multiple error conditions I reduced to this.

(Seen at VS 2015 Enterprise Update 1 on Win10 x64)

**Comment by HJLebbink** [comment]
Hi Dtr, thanx for reporting. Hitting enter on the first line of the file yields NPE. I've fixed this. I guess you were building from source, then the fix will be available immediately.
