### ISSUE TITLE
Lebbink my dude

### ISSUE THREAD

**Issue by ProfileSeeker** [HJLebbink/asm-dude#71]
Can you at least tell us how this happened?
Did I install wrong npm package?
I knew npm is a bad thing.

**Comment by HJLebbink** [comment]
Sorry to spam you all.

I don't know who or how someone added about 4000 GitHub account to the watch list of this project. Many of you who are (obviously -- life is too short) not interested in assembly programming most likely have their GitHub accounts compromised starting from Saturday.  

Some hacker thought it would be funny to add users to Microsoft tools used by hacker (it was probably a Linux user, many other tools were also 'beneficiaries', https://github.com/x64dbg/x64dbg got 35K stars)

Change *ALL* your passwords and unwatch this project.
