### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by asaah18** [HJLebbink/asm-dude#74]
my visual studio version is 2013

[VSIXInstaller_c1f097ea-0e70-4a3f-9d3d-57f4e77231a9.log](https://github.com/HJLebbink/asm-dude/files/1776118/VSIXInstaller_c1f097ea-0e70-4a3f-9d3d-57f4e77231a9.log)

**Comment by HJLebbink** [comment]
AsmDude is only works (as advertised) on VS2015 and VS2017.
