### ISSUE TITLE
"Comment Selection" and "Uncomment Selection" are disabled in Visual Studio 2017

### ISSUE THREAD

**Issue by huangfaqian** [HJLebbink/asm-dude#76]
![default](https://user-images.githubusercontent.com/12290276/38187127-df0935f2-3688-11e8-8fea-c23b5ee3a698.png)

**Visual Studio Info**

Microsoft Visual Studio Professional 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA250
Microsoft Visual C++ 2017

AsmDude   1.9.4.2
Syntax highlighting, code completion and code folding for assembly (.asm, .cod, .inc, .s) source code.

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by huangfaqian** [comment]
This issue can only be reproduced in Assembly (.asm) source window, not in cpp source window.

**Comment by HJLebbink** [comment]
That is a feature that is not supported. I you know how to implement it, I could add this. I'll put it on the TODO list

**Comment by duco232** [comment]
Henk jan gast waarom krijg ik die gekke minecraft mailtjes van je gek
