### ISSUE TITLE
Incorrect syntax highlighting for remarks in the disassembly window

### ISSUE THREAD

**Issue by matt-elson** [HJLebbink/asm-dude#77]
When using VSLinux to debug a Linux program in VS2015, I found ASM Dude will mistakenly look some instructions as remark(when enabling ASM Dude's syntax highlighting, please see screenshot2), could you tell me how to fix the problem? thanks.
Screenshot1:
![asmdude1](https://user-images.githubusercontent.com/2929106/39039758-aec5bb52-44b8-11e8-920d-e763b2b75ae0.png)
Screenshot2:
![asmdude2](https://user-images.githubusercontent.com/2929106/39039889-ead4edde-44b8-11e8-81c0-3c51ea7ac99d.png)

**Comment by HJLebbink** [comment]
Thank you for reporting this.

The content of the Disassembly window is just plain text. AsmDude has some (ugly) heuristics on what disassembly code is and what the interleaved source code (Fortran, C, etc). For Intel assembly these heuristics work good enough. One rule in the heuristics is that if the line contains a mnemonic, it is assembly, 

I didn't know one could have AT&T syntax in the disassembly window. Did you use a different disassembler?

I'll update the heuristics to better judge what is disassembly and what is source code.

**Comment by matt-elson** [comment]
Thanks for quickly reply.

**Comment by HJLebbink** [comment]
Hi Matt,

I'm trying to fix this without a working example. Could you confirm that (overall) the only highlighting errors occur when the line contains an instruction (such as callq with the suffix b/w/l/q)?

Regards HJ

**Comment by HJLebbink** [comment]
Could you please confirm whether this is fixed in version 1.9.5.0+?
