### ISSUE TITLE
Adding custom file extensions to be opened with AsmDude

### ISSUE THREAD

**Issue by Tinister** [HJLebbink/asm-dude#8]
It would be really nice to allow custom file extensions (e.g. "*.iasm") to be opened with AsmDude.

The Visual Studio Way of doing that usually is going to Tools -> Options -> Text Editor -> File Extension, then typing in the extension and which editor to open it with.  However, I have no clue how much effort it is to make Visual Studio recognize AsmDude as an "editor".

**Comment by HJLebbink** [comment]
Yes that would indeed be a nice features.

It is very easy to add a file extension in the source code, but sadly it is very difficult to do this such that it can be configured in e.g. Tools>Options>AsmDude. I guess it is possible, but I'm not aware of a method to achieve this. If you know how to do this, please let me know.

You could clone the repository, add the following lines, compile the .vsix, and install it. You need not wait for a next release.

If you insert:

`[Export]`
`[FileExtension(".iasm")]`
`[ContentType(AsmDudePackage.AsmDudeContentType)]`
`internal static FileExtensionToContentTypeDefinition AsmFileType_iasm = null;`

at line 94 in [AsmClassifier](https://github.com/HJLebbink/asm-dude/blob/master/VS/CSHARP/asm-dude-vsix/SyntaxHighlighting/AsmClassifier.cs), you would be done.

If you think this a common extension for assembly files, I could add it for you.
