### ISSUE TITLE
Recent Visual Studio updates broke label analysis

### ISSUE THREAD

**Issue by DrP3pp3r** [HJLebbink/asm-dude#81]
Label analysis is completely broken.

![grafik](https://user-images.githubusercontent.com/17963997/40490706-9085a7e6-5f6c-11e8-9635-0c06254f180d.png)

Asm Dude v1.9.4.2
Visual Studio 2017 v15.7.2

**Comment by nsn-e** [comment]
same issue here.

**Comment by LeifEriccson** [comment]
why do i keep getting linked to random github threads...

**Comment by McSwaggens** [comment]
I'm getting this too, really annoying...

**Comment by HJLebbink** [comment]
Thank you for waiting and for for bringing this to my attention. I has been fixed in the next version after 1.9.4.2. 

In the upgrade from VS 14.6 to 14.7 something has changed. I hoped I would fix itself with a new VS update, but it didn't.
