### ISSUE TITLE
Add some new features

### ISSUE THREAD

**Issue by sajadbanooie** [HJLebbink/asm-dude#9]
Add support for segment registers, extern, nasm macros ,addressing modes and more syntax highlighting

**Comment by HJLebbink** [comment]
Hi sajadbanooie,

I understand the convenience of syntax highlighting (and code completion and documentation) for segment registers and nasm macros, I have added these to the Feature Requests.

But what would you like to do with externs and addressing modes?

**Comment by sajadbanooie** [comment]
extern: to extern some c functions in order to mix c and asm like using c io functions

addressing modes: to use odder segments and also you can use visual studio to develop your own OS
[http://wiki.osdev.org/Visual_Studio](url)

please add the .bss segment ,RESB and Friends to your project too.

**Comment by HJLebbink** [comment]
You mean to add the keywords "extern", ".bss" etc such that they get colorized and they can be auto completed.

**Comment by sajadbanooie** [comment]
yup.its simple I guess.
