### ISSUE TITLE
asm dude in visual studio 2019 preview

### ISSUE THREAD

**Issue by AHUMANTHATISHUMAN** [HJLebbink/asm-dude#92]
On [visual studio marketplace](https://marketplace.visualstudio.com/items?itemName=Henk-JanLebbink.AsmDude), it says that this supports visual studio 2019. Trying to install it, however, says that it contains prerequisites that can not be found.

**Comment by AHUMANTHATISHUMAN** [comment]
This could be because I have both 2017 and 2019 preview installed.

**Comment by HJLebbink** [comment]
I'm looking into it. I'll either try to remove the unexpected listing that AsmDude is compatible with VS2019, or I'll try to fix the current issues with VS2019, but the latter are more complicated than advertised.

**Comment by HJLebbink** [comment]
Visual studio 2019 (and 2015 & 2017) are supported in version 1.9.6.0

**Comment by coreteam** [comment]
yeah im subscribed to it, and the mute the thread link doesnt even work.
what a piece of shit

**Comment by Trass3r** [comment]
Doesn't work for me with the Preview channel version of VS2019. It does not get listed and installing the vsix manually does not work either.
It installed fine in the Release version.
