### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by silentaim** [HJLebbink/asm-dude#93]
Would be nice to have the following keywords added, color-coding not necessary:

-ADDR
-OFFSET
-NEAR
-FAR

**Comment by fmjaguar7** [comment]
take me off this mailing list

**Comment by HJLebbink** [comment]
Adding these keywords for color-coding is easy, but other features are more complicated. What features that are useful were you thinking of?

**Comment by silentaim** [comment]
Just the keywords for now would be nice for completeness; you already included everything else. Perhaps error checking ADDR/OFFSET when you use/don't use it inside an INVOKE. 

Thanks @HJLebbink

**Comment by Leaeaxedx** [comment]
Asm instruction vptest is not highlighted in latest asm.

**Comment by HJLebbink** [comment]
@Leaeaxedx vptest is not an instruction as far as i know. Could you point me to an official documentation with that instruction?

**Comment by Leaeaxedx** [comment]
At   https://software.intel.com/en-us/articles/intel-sdm#combined

you can get Combined Volume Set of Intel® 64 and IA-32 Architectures
Software Developer’s Manuals
<https://software.intel.com/en-us/articles/intel-sdm#combined>, April 2019.

I extracted and attached the page regarding PTEST instruction. VPTEST is a
part of AVX and AVX 2 instruction set.




V V tor., 14. maj 2019 ob 23:27 je oseba Henk-Jan Lebbink <
notifications@github.com> napisala:

**Comment by HJLebbink** [comment]
Yes, of course. Thanx for pointing that out. Will be fixed!

**Comment by Leaeaxedx** [comment]
No, THANK YOU for the ASMDUDE!!!!

V V sre., 15. maj 2019 ob 12:06 je oseba Henk-Jan Lebbink <
notifications@github.com> napisala:

**Comment by HJLebbink** [comment]
@Leaeaxedx I'm a bit confused. Do you have an assembler that accepts `vptest` as an instruction? The documentation only gives opcodes for `VPTESTMB`, `VPTESTMW`, `VPTESTMD `and `VPTESTMQ`.

**Comment by Leaeaxedx** [comment]
I'm using Uasm assembler ( http://www.terraspace.co.uk/uasm.html)

There is attached testing disassembly for VPTEST instruction. The
instruction is from AVX architecture and It works on my I7 from 2010.
VPTEST sets Z flag if the result of bitwise AND is zero. The instructions
VPTESTMB, VPTESTMW, VPTESTMD are from AVX512 architecture. They set the
mask according to bitwise AND result.

[image: Dissasembler.png]
I also attached VPTEST manual page from "Intel® 64 and IA-32 Architectures
Software Developer's Manual" all volumens (A;B...)

Hope this will help you a bit. Don't hesitate to contact me again.

Have a nice coding!  ;)

V V ned., 26. maj 2019 ob 15:43 je oseba Henk-Jan Lebbink <
notifications@github.com> napisala:

**Comment by Leaeaxedx** [comment]
FYI: The AsmDude recognizes  VPSHLB (W/D/Q) as AVX instructions, which are
not valid instructions.

Regards,

Igor
