### ISSUE TITLE
install error in Ubuntu

### ISSUE THREAD

**Issue by grayterm** [HJLebbink/asm-dude#96]
"extension/package.json not found inside zip"
error when trying to install in Visual Studio Code 1.30.2 in Ubuntu 18.10
it would be great if the extension worked in Linux, too. Cheers

**Comment by HJLebbink** [comment]
How did you get VS Code to even consider installing AsmDude.vsix?
AsmDude is not intended to work on VS Code.

**Comment by jason1000rr** [comment]
Stop
