### ISSUE TITLE
VS 2012 support?

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [HJLebbink/asm-dude#97]
Would it be possible to enable VS 2012 (Version 11.0) support, so I could at least try to install and report back the results?

**Comment by HJLebbink** [comment]
Hi, It is generally not possible to back-port plugins to versions before 15.0 easily. I'm not an expert in how the plugin structure changed between v14 and v15 but but most of the features in AsmDude rely on infrastructure introduced in v15.

**Comment by St0fF-NPL-ToM** [comment]
Hi Henk-Jan,

well, that's sad for me.  Thanks for your great work anyhow and please
continue with the good stuff ;)

Cheers,
Stefan <St0fF^Neoplasia^theObsessedManiacs> Kaps


Henk-Jan Lebbink schrieb:
